@echo off
echo Starting FastAPI backend server...
cd /d "%~dp0"
if not exist ".venv\Scripts\activate.bat" (
    echo Creating virtual environment...
    python -m venv .venv
)
call .venv\Scripts\activate.bat
echo Installing dependencies...
pip install fastapi pydantic python-multipart uvicorn
echo Starting server on port 8000...
uvicorn app.main:app --reload --host 0.0.0.0 --port 8000